[package]
name = "native_app"
version = "0.1.0"
authors = ["Douady Pâris <paris.douady@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

futures       = { version = "0.3.4", default-features = false, features = ["executor"] }
bytemuck      = "1.2.0"
egregoria     = { path = "../egregoria" }
geom          = { path = "../geom" }
wgpu_engine   = { path = "../wgpu_engine" }
common        = { path = "../common" }
mint          = "0.5.6"
imgui-inspect = { path = "../imgui-inspect" }
imgui-inspect-derive = { path = "../imgui-inspect-derive" }
imgui-wgpu    = { git = "https://github.com/Yatekii/imgui-wgpu-rs" }
imgui-winit-support = "0.5.0"
map_model     = { path = "../map_model" }
env_logger    = "0.7.1"
log           = "0.4.11"
inline_tweak  = "1.0.6"
imgui         = "0.5.0"
legion        = { version = "0.3.0", default-features = false, features = ["codegen", "serialize", "extended-tuple-impls"] }
ordered-float = "2.0.0"
serde         = "1.0.117"
rodio         = { version = "0.13.0", default-features = false, features = ["vorbis"] }
slotmap       = "0.4.0"
winit         = "0.22"
