[workspace]
members = [
    "egregoria",
    "gui",
    "geom",
    "headless-cli",
    "imgui-inspect",
    "imgui-inspect-derive",
    "map_model",
    "mods",
    "common",
    "native_app",
    "wgpu_engine",
    "souls",
]

default-members = ["native_app"]

# Set the settings for build scripts and proc-macros.
[profile.dev.build-override]
opt-level = 1

[profile.dev.package."*"]
opt-level = 2

[profile.dev.package.common]
opt-level = 2

[profile.dev.package.egregoria]
opt-level = 0

[profile.dev.package.map_model]
opt-level = 0

[profile.dev.package.native_app]
opt-level = 0

[profile.dev.package.imgui-inspect]
opt-level = 1

[profile.dev.package.imgui-inspect-derive]
opt-level = 1

[profile.release]
#debug = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
