[package]
name = "common"
version = "0.1.0"
authors = ["Paris DOUADY <paris.douady@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode       = "1.2.1"
serde         = "1.0"
serde_json    = "1.0.59"
log           = "0.4.11"
legion        = { version = "0.3.0", default-features = false, features = ["codegen", "serialize", "extended-tuple-impls"] }
geom          = { path = "../geom" }
imgui-inspect = { path = "../imgui-inspect" }
imgui-inspect-derive = { path = "../imgui-inspect-derive" }
lazy_static   = "1.4.0"
arc-swap      = "0.4.7"
